image: alpine/edge
packages:
  - hugo
  - hut
oauth: pages.sr.ht/PAGES:RW
sources:
  - https://git.sr.ht/~sircmpwn/harelang.org
tasks:
tasks:
- build: |
    cd harelang.org
    hugo
- upload: |
    cd harelang.org
    hut pages publish -d harelang.org ./public/
